### ISSUE TITLE
SVG support

### ISSUE THREAD

**Issue by clayrat** [sharkdp/purescript-flare#13]
Is there a plan to support vector graphics as well? I can't seem to find any standalone SVG lib for Purescript however..

**Comment by clayrat** [comment]
The easiest way is probably to extend Smolder first?

**Comment by sharkdp** [comment]
I'd love to support SVG in some way. But as you said, this does not really depend on Flare itself. Extending Smolder would be one option. If there is an existing SVG library somewhere, you could already use it via 'runFlareWith'.

Another very cool way would be if purescript-drawing had a SVG backend in addition to the Canvas backend.
