### ISSUE TITLE
Use dom attributes.

### ISSUE THREAD

**Issue by xgrommx** [sharkdp/purescript-flare#18]
Hello @sharkdp Awesome work! But sometime we need use specific class, type, id, etc. Will be better have support for this ability in purescript-flare. Thanks.

**Comment by sharkdp** [comment]
I'm not exactly sure, what you mean... would you like to have support for custom CSS classes on the input elements (instead of `flare-input-int-number`, for example)?

**Comment by xgrommx** [comment]
@sharkdp yes, smth like this one.

**Comment by sharkdp** [comment]
Closing this in favor of #23.
