### ISSUE TITLE
Try Flare is down

### ISSUE THREAD

**Issue by jmatsushita** [sharkdp/purescript-flare#21]
Apparently because compile.purescript.org is down?

![image](https://cloud.githubusercontent.com/assets/356097/20093782/7b5e8db2-a59e-11e6-918c-48c98baa1cba.png)

**Comment by sharkdp** [comment]
Thank you for the report. Unfortunately, it has been down for some time, because I did not get around to getting it working again. I'll work on it, as soon as trypurescript has been ported to PureScript 0.10.

**Comment by sharkdp** [comment]
Try Flare is finally back online: http://try.purescript.org/?backend=flare
