### ISSUE TITLE
Allow to specify id of generated controls

### ISSUE THREAD

**Issue by jmatsushita** [sharkdp/purescript-flare#23]
Hi there,

Trying to workaround #22 I'm looking at trying to create a layer of mirrored controls that I'll layer in the output to have more possibilities for layout. However, right now I have to select controls using their generated numerical html ids such as `flare-component-2`.

It would be great if it was possible to control the html `id` of flare components! 

Cheers,

Jun

**Comment by sharkdp** [comment]
:+1: if there is a way to add this without having to replicate every single UI-element function...

**Comment by sharkdp** [comment]
Closing this for now.
