### ISSUE TITLE
Support textarea in addition to text field

### ISSUE THREAD

**Issue by 0dB** [sharkdp/purescript-flare#25]
I am using purescript-flare to transform data entered into a textfield into an HTML table, applying some processing on the way (time-sheet data). It would be cool to be able to use a textarea instead so that users see their raw input with newlines and all.

(It is my understanding that this would mean adding a foreign function that creates a textarea component. Unfortunately my JS know-how is practically zero otherwise I would try it myself.)

**Comment by sharkdp** [comment]
This should be supported now. Would be great if you could test this.

**Comment by 0dB** [comment]
Works, thank you very much!

Now I can see all rows of data, and, most importantly, parse lines via `\n`.

**Comment by sharkdp** [comment]
Thanks for testing!
