### ISSUE TITLE
Update to PureScript 0.13

### ISSUE THREAD

**Issue by FranklinChen** [sharkdp/purescript-flare#31]
Is there a plan to update to PureScript 0.13? I do see that this would require and update for `purescript-drawing` https://github.com/paf31/purescript-drawing/issues/32

**Comment by sharkdp** [comment]
I probably won't have time to work on it myself, but in principle: yes.

**Comment by KovaxG** [comment]
Updated a dependency so the project will compile at least.

https://github.com/sharkdp/purescript-flare/pull/32

**Comment by sharkdp** [comment]
Thank you. The tests look fine after building (see README). I pushed a new v6.0.0 tag. Unfortunately, `pulp publish` fails:
```
* Uploading documentation to Pursuit...
* Failed reading: not a valid json value
* ERROR: Expected an HTTP 201 response from Pursuit, got: 400
```

**Comment by FranklinChen** [comment]
I put flare into https://github.com/purescript/package-sets/pull/473

**Comment by sharkdp** [comment]
Thank you
